app = "bip-web-prd"
primary_region = "bos"

[build]
dockerfile = "Dockerfile"

  [build.args]
  NODE_VERSION = "22"

[env]
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = "off"
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/health"
  protocol = "http"
  timeout = "5s"

  [http_service.concurrency]
  hard_limit = 1_000
  soft_limit = 800
  type = "connections"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1_024