app = "bip-web-prd"
primary_region = "bos"

[build]
dockerfile = "Dockerfile"
[build.args]
NODE_VERSION = "22"

[env]
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 800

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health"
protocol = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
