services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "development"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "bip_dev"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U development -d bip_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: bip-postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: bip-redis

volumes:
  postgres_data:
  redis_data: