name: bip

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    networks:
      - bip-network

networks:
  bip-network:
    driver: bridge

volumes:
  redis_data: