name: Deploy Web App
on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Type Check
        run: turbo typecheck
      
      - name: Biome Check
        run: turbo lint
      
      - name: Run tests
        run: turbo test
      
      - name: Build
        run: turbo build
      
      - name: Install Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 