name: Deploy Web App
on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'bun.lockb'
      - '.github/**'
      - '!README.md'

concurrency:
  group: deploy-web-app
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.4

      # Cache Bun dependencies
      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            **/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: cd packages/core && bun prisma:generate:prod
      
      - name: Build
        run: bun run build
      
      - name: Install Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly
        run: flyctl deploy --strategy bluegreen --remote-only --config apps/web/fly.toml --dockerfile apps/web/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 