name: Deploy Web App
on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/**'
jobs:
  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # Setup node with built-in pnpm caching
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      # Cache the pnpm store
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
            node_modules
            **/node_modules
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --recursive

      - name: Type Check
        run: |
          pnpm --filter @bip/domain typecheck
          pnpm --filter @bip/core typecheck
          pnpm --filter @bip/web typecheck
      
      - name: Biome Check
        run: pnpm lint
      
      # - name: Run tests
      #   run: pnpm test
      
      - name: Build
        run: pnpm build
      
      - name: Install Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --config apps/web/fly.toml --dockerfile apps/web/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} 